- hosts: localhost
  gather_facts: False

  vars_files:
    - "vars/ec2/{{ launch_environment }}.yml"

  vars:
      delete: false
      tag_class: "*"
      az: "{{ aws_region }}{{ availability_zone | default('*') | lower }}"

  tasks:

    - name: Get subnet IDs
      command: "bin/list_vpc_resources -t subnet -r {{ aws_region }} -f tag:environment={{launch_environment}}"
      register: raw_subnet_id_list
      when: not delete

    - set_fact:
        subnet_ids: "{{ raw_subnet_id_list.stdout | from_json }}"
      when: not delete

    - name: Launch ec2 instances
      ec2:
        region: "{{ aws_region }}"
        zone: "{{ item.zone }}"
        ec2_access_key: "{{ ec2_access_key }}"
        ec2_secret_key: "{{ ec2_secret_key }}"
        instance_type: "{{ item.instance_type }}"
        image: "{{ item.image }}"
        keypair: "{{ ec2_keypair }}"
        instance_tags: "{{ item.instance_tags }}"
        exact_count: "{{ item.exact_count }}"
        count_tag: "{{ item.count_tag }}"
        group: "{{ item.group }}"
        assign_public_ip: yes # Bootstrapping for development
        vpc_subnet_id: "{{ subnet_ids[item.subnet_name] }}"
        wait: true
      register: ec2
      with_items: ec2_instances
      when: not delete and (tag_class == "*" or tag_class == item.instance_tags.class) and (az == "{{aws_region}}*" or az == item.zone)

    - name: Add new instance to host group
      add_host: hostname={{ item.instances[0].private_ip }} groupname=instances
      with_items: ec2.results
      when: item.instances[0] is defined and not delete

    - name: Get all instance IDs
      command: "/usr/local/bin/list_instances -r {{ aws_region }} -H ID -f tag:environment={{launch_environment}},tag:class={{tag_class}},availability_zone={{az}} -t"
      register: raw_instance_list
      when: delete

    - set_fact: instance_ids="{{raw_instance_list.stdout_lines}}"
      when: delete

    - name: Terminate the instances
      local_action:
        module: ec2
        instance_ids: "{{ item }}"
        state: absent
        region: 'eu-west-1'
        wait: false
      with_items: instance_ids
      when: delete

- name: Private DNS.
  hosts: instances
  gather_facts: no

  pre_tasks:
    - wait_for: port=22

  roles:
    - dns

