---
- name: Gather facts
  action: ec2_facts

- name: "Get Instance tags"
  local_action: ec2_tag resource="{{ ansible_ec2_instance_id }}" state=list region="{{ aws_region }}"
  register: instance_tags

- set_fact: hostname="{{ instance_tags['tags']['Name'] | lower | reverse | truncate(10, True, '') | reverse }}"

- name: "Set hostname"
  hostname: name="{{ hostname }}"
  sudo: yes

- name: "Add hostname to /etc/hosts"
  lineinfile: dest=/etc/hosts line="127.0.0.1 {{ hostname }}.{{ private_hosted_zone }} {{ hostname }}" owner=root group=root mode=0644
  sudo: yes

- name: "Add DNS entry"
  local_action: >
    route53 command="create"
    private_zone=true
    zone="{{ private_hosted_zone }}"
    record="{{ hostname }}.{{ private_hosted_zone }}"
    type="A" value="{{ ansible_ec2_local_ipv4 }}"
    overwrite=true

